coordinator: "true"
node-scheduler.include-coordinator: "false"
http-server.http.port: "8080"
query:
  max-memory: "50GB"
  max-memory-per-node: "1GB"
  max-total-memory-per-node: "2GB"
discovery-server.enabled: "NULL"
discovery.uri: "=http://${DISCOVERY_SERVER_HOSTNAME:=0.0.0.0}:${DISCOVERY_SERVER_PORT:=8080}}"
