coordinator: "true"
node-scheduler:
  include-coordinator: "false"
  max-splits-per-node: "100"
  max-pending-splits-per-task: "10"
  min-candidates: "10"
  policy: "uniform"
  network-topology:
    segments: "NULL"
    type: "NULL"
    file: "NULL"
    refresh-period: "NULL"
http-server:
  http.port: "8080"
  log:
    enabled: "true"
    compression.enabled: "true"
    path: "var/log/http-request.log"
    max-history: "15"
    max-size: "NULL"
query:
  max-memory: "50GB"
  max-total-memory: "NULL"
  max-memory-per-node: "1GB"
  max-total-memory-per-node: "2GB"
  max-execution-time: "NULL"
  max-run-time: "NULL"
  max-stage-count: "NULL"
  max-history: "NULL"
  min-expire-age: "NULL"
discovery-server.enabled: "NULL"
discovery.uri: "=http://${DISCOVERY_SERVER_HOSTNAME:=0.0.0.0}:${DISCOVERY_SERVER_PORT:=8080}"
join-distribution-type: "AUTOMATIC"
redistribute-writes: "true"
memory:
  heap-headroom-per-node: "NULL"
spill-enabled: "false"
spill-order-by: "true"
spill-window-operator: "true"
spiller-spill-path: "NULL"
spiller-max-used-space-threshold: "0.9"
spiller-threads: "4"
max-spill-per-node: "NULL"
query-max-spill-per-node: "NULL"
aggregation-operator-unspill-memory-limit: "NULL"
spill-compression-enabled: "false"
spill-encryption-enabled: "false"
exchange:
  client-threads: "25"
  concurrent-request-multiplier: "3"
  data-integrity-verification: "ABORT"
  max-buffer-size: "32MB"
  max-response-size: "16MB"
sink:
  max-buffer-size: "32MB"
task:
  concurrency: "16"
  http-response-threads: "100"
  http-timeout-threads: "3"
  info-update-interval: "3s"
  max-partial-aggregation-memory: "16MB"
  max-worker-threads: "NULL"
  min-drivers: "NULL"
  writer-count: "1"
scale-writers: "false"
writer-min-size: "32MB"
optimizer:
  dictionary-aggregation: "false"
  optimize-hash-generation: "true"
  optimize-metadata-queries: "false"
  push-aggregation-through-outer-join: "true"
  push-table-write-through-union: "true"
  join-reordering-strategy: "AUTOMATIC"
  max-reordered-joins: "NULL"
log:
  path: "var/log/server.log"
  max-history: "30"
  max-size: "100MB"
regex-library: "JONI"
re2j:
  dfa-states-limit: "2147483647"
  dfa-retries: "5"
