apiVersion: v1
kind: ConfigMap
metadata:
  name: presto-coordinator-config
  labels:
    app: presto
    unit: coordinator
data:
  COORDINATOR: "true"
  NODE_SCHEDULER_INCLUDE_COORDINATOR: "false"
  QUERY_MAX_MEMORY: "5GB"
  QUERY_MAX_MEMORY_PER_NODE: "1GB"
  DISCOVERY_SERVER_ENABLED: "true"
  NODE_ENVIRONMENT: "production"
  CONNECTORS: |
    hive
  HIVE_METASTORE_URI: "thrift://hive-metastore-svc:9083"
