apiVersion: v1
kind: Service
metadata:
  name: presto-coordinator-svc
  labels:
    app: presto
    unit: coordinator
spec:
  selector:
    app: presto
    unit: coordinator
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
