apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: presto-sa-rolebinding
  labels:
    unit: serviceaccount-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: presto-sa-role
subjects:
  - kind: ServiceAccount
    name: presto-sa