version: "3.5"
services:
  presto-coordinator:
    image: mpolatcan/presto:344-java11
    container_name: presto-coordinator
    hostname: presto-coordinator
    environment:
      COORDINATOR: "true"
      NODE_SCHEDULER_INCLUDE_COORDINATOR: "false"
      QUERY_MAX_MEMORY: "5GB"
      QUERY_MAX_MEMORY_PER_NODE: "1GB"
      DISCOVERY_SERVER_ENABLED: "true"
      NODE_ENVIRONMENT: "production"
    ports:
      - 8080:8080

  presto-worker:
    image: mpolatcan/presto:344-java11
    environment:
      COORDINATOR: "false"
      QUERY_MAX_MEMORY: "5GB"
      QUERY_MAX_MEMORY_PER_NODE: "1GB"
      COORDINATOR_HOSTNAME: "presto-coordinator"
      NODE_ENVIRONMENT: "production"

  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: "presto"
      POSTGRES_PASSWORD: "presto"
    ports:
      - 5432:5432
