apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
  labels:
    unit: hive-metastore
spec:
  selector:
    matchLabels:
      unit: hive-metastore
  template:
    metadata:
      labels:
        unit: hive-metastore
    spec:
      serviceAccountName: presto-sa
      containers:
      - name: hive-metastore
        image: mpolatcan/hive:3.1.2-hadoop-3.1.4-java8
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: hive-metastore-config
        ports:
          - containerPort: 9083
      securityContext:
        fsGroup: 1000