apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: presto-worker
  labels:
    unit: worker
spec:
  serviceName: presto-worker
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      unit: worker
  template:
    metadata:
      labels:
        unit: worker
    spec:
      serviceAccountName: presto-sa
      containers:
      - name: presto-worker
        image: mpolatcan/presto:344-java11
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: presto-worker-config
        ports:
        - containerPort: 8080
      securityContext:
        fsGroup: 1000
