apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: presto
commonLabels:
  environment: development
bases:
  - ../base
patchesStrategicMerge:
  - deployment/hive-metastore-patch-deployment.yaml
  - deployment/presto-coordinator-patch-deployment.yaml
  - deployment/presto-worker-patch-deployment.yaml
configMapGenerator:
  - name: hive-metastore-config
    behavior: merge
    envs:
      - configuration/hive-metastore.env
  - name: presto-coordinator-config
    behavior: merge
    envs:
      - configuration/presto-coordinator.env
  - name: presto-worker-config
    behavior: merge
    envs:
      - configuration/presto-worker.env