config_loader_sh_template: |
  #!/usr/bin/env bash
  function load_config() {{
      if [[ "$2" != "NULL" ]]; then
          printf "$1=$2\n" >> "${{PRESTO_CONF_DIR}}/$3"
      fi
  }}

  # Load Jvm configurations
  cat <<EOF > ${{PRESTO_CONF_DIR}}/jvm.config
  -server
  -Xmx${{JVM_HEAP_SIZE:=16G}}
  -XX:-UseBiasedLocking
  -XX:+UseG1GC
  -XX:G1HeapRegionSize=${{JVM_G1_HEAP_REGION_SIZE:=32M}}
  -XX:+ExplicitGCInvokesConcurrent
  -XX:+ExitOnOutOfMemoryError
  -XX:+HeapDumpOnOutOfMemoryError
  -XX:ReservedCodeCacheSize=${{JVM_RESERVED_CODE_CACHE_SIZE:=512M}}
  -XX:PerMethodRecompilationCutoff=${{JVM_PER_METHOD_RECOMPILATION_CUTOFF:=10000}}
  -XX:PerBytecodeRecompilationCutoff=${{JVM_PER_BYTECODE_RECOMPILATION_CUTOFF:=10000}}
  -Djdk.attach.allowAttachSelf=true
  -Djdk.nio.maxCachedBufferSize=${{JVM_JDK_NIO_MAX_CACHED_BUFFER_SIZE:=2000000}}
  EOF

  # Load Presto main, node and connector configurations
  {load_fn_calls}

  CONNECTOR_CONFIG_FILES=$(ls ${{PRESTO_CONNECTOR_CONF_DIR}})

  if [[ "${{CONNECTORS}}" != "" ]]; then
      for CONNECTOR_CONFIG_FILE in ${{CONNECTOR_CONFIG_FILES[@]}}; do
          for CONNECTOR in ${{CONNECTORS[@]}}; do
              if [[ "${{CONNECTOR}}.properties" != "${{CONNECTOR_CONFIG_FILE}}" ]]; then
                  echo "Removing connector config: \"${{CONNECTOR}}.properties\""
                  rm ${{PRESTO_CONNECTOR_CONF_DIR}}/${{CONNECTOR_CONFIG_FILE}}
              fi
          done
      done
  else
      echo "There is no defined connectors, so all generated configurations will be deleted!"
      rm ${{PRESTO_CONNECTOR_CONF_DIR}}/*.properties
  fi

config_files:
  - path: presto_configs/config.yaml
    filename: config.properties
  - path: presto_configs/node.yaml
    filename: node.properties
  - path: presto_configs/connectors/accumulo.yaml
    filename: catalog/accumulo.properties
  - path: presto_configs/connectors/bigquery.yaml
    filename: catalog/bigquery.properties
  - path: presto_configs/connectors/cassandra.yaml
    filename: catalog/cassandra.properties
  - path: presto_configs/connectors/druid.yaml
    filename: catalog/druid.properties
  - path: presto_configs/connectors/elasticsearch.yaml
    filename: catalog/elasticsearch.properties
  - path: presto_configs/connectors/gsheets.yaml
    filename: catalog/gsheets.properties
  - path: presto_configs/connectors/hive.yaml
    filename: catalog/hive.properties
  - path: presto_configs/connectors/jmx.yaml
    filename: catalog/jmx.properties
  - path: presto_configs/connectors/kafka.yaml
    filename: catalog/kafka.properties
  - path: presto_configs/connectors/kinesis.yaml
    filename: catalog/kinesis.properties
  - path: presto_configs/connectors/kudu.yaml
    filename: catalog/kudu.properties
  - path: presto_configs/connectors/memsql.yaml
    filename: catalog/memsql.properties
  - path: presto_configs/connectors/mongodb.yaml
    filename: catalog/mongodb.properties
  - path: presto_configs/connectors/mysql.yaml
    filename: catalog/mysql.properties
  - path: presto_configs/connectors/oracle.yaml
    filename: catalog/oracle.properties
  - path: presto_configs/connectors/phoenix.yaml
    filename: catalog/phoenix.properties
  - path: presto_configs/connectors/pinot.yaml
    filename: catalog/pinot.properties
  - path: presto_configs/connectors/postgresql.yaml
    filename: catalog/postgresql.properties
  - path: presto_configs/connectors/prometheus.yaml
    filename: catalog/prometheus.properties
  - path: presto_configs/connectors/redis.yaml
    filename: catalog/redis.properties
  - path: presto_configs/connectors/redshift.yaml
    filename: catalog/redshift.properties
  - path: presto_configs/connectors/sqlserver.yaml
    filename: catalog/sqlserver.properties
  - path: presto_configs/connectors/thrift.yaml
    filename: catalog/thrift.properties
output_dir: ../../base