apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: presto-coordinator-rolebinding
  labels:
    app: presto
    unit: serviceaccount-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: presto-coordinator-role
subjects:
  - kind: ServiceAccount
    name: presto-coordinator-sa