apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
  labels:
    app: presto
    unit: hive-metastore
spec:
  selector:
    matchLabels:
      app: presto
      unit: hive-metastore
  template:
    metadata:
      labels:
        app: presto
        unit: hive-metastore
    spec:
      containers:
      - name: hive-metastore
        image: mpolatcan/hive:2.3.7-hadoop-2.7.7-java8
        envFrom:
          - configMapRef:
              name: hive-metastore-config
        ports:
          - containerPort: 9083
